// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_manager.proto

// Protobuf Java Version: 3.25.1
package com.vehicle.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vehicle.grpc.Empty)
    com.google.protobuf.MessageOrBuilder {
}
