// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_manager.proto

// Protobuf Java Version: 3.25.1
package com.vehicle.grpc;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vehicle.grpc.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
