// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_manager.proto

// Protobuf Java Version: 3.25.1
package com.vehicle.grpc;

public interface RouteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vehicle.grpc.RouteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.vehicle.grpc.RouteResult result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  int getResultValue();
  /**
   * <code>.com.vehicle.grpc.RouteResult result = 1;</code>
   * @return The result.
   */
  com.vehicle.grpc.RouteResult getResult();
}
