// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_manager.proto

// Protobuf Java Version: 3.25.1
package com.vehicle.grpc;

public interface RouteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vehicle.grpc.Route)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.vehicle.grpc.Event events = 1;</code>
   */
  java.util.List<com.vehicle.grpc.Event> 
      getEventsList();
  /**
   * <code>repeated .com.vehicle.grpc.Event events = 1;</code>
   */
  com.vehicle.grpc.Event getEvents(int index);
  /**
   * <code>repeated .com.vehicle.grpc.Event events = 1;</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .com.vehicle.grpc.Event events = 1;</code>
   */
  java.util.List<? extends com.vehicle.grpc.EventOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <code>repeated .com.vehicle.grpc.Event events = 1;</code>
   */
  com.vehicle.grpc.EventOrBuilder getEventsOrBuilder(
      int index);

  /**
   * <code>string vehicle = 2;</code>
   * @return The vehicle.
   */
  java.lang.String getVehicle();
  /**
   * <code>string vehicle = 2;</code>
   * @return The bytes for vehicle.
   */
  com.google.protobuf.ByteString
      getVehicleBytes();
}
