// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_manager.proto

// Protobuf Java Version: 3.25.1
package com.vehicle.grpc;

public interface RoutesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vehicle.grpc.Routes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
   */
  java.util.List<com.vehicle.grpc.Route> 
      getRouteList();
  /**
   * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
   */
  com.vehicle.grpc.Route getRoute(int index);
  /**
   * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
   */
  int getRouteCount();
  /**
   * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
   */
  java.util.List<? extends com.vehicle.grpc.RouteOrBuilder> 
      getRouteOrBuilderList();
  /**
   * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
   */
  com.vehicle.grpc.RouteOrBuilder getRouteOrBuilder(
      int index);
}
