// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_manager.proto

// Protobuf Java Version: 3.25.1
package com.vehicle.grpc;

/**
 * Protobuf type {@code com.vehicle.grpc.Routes}
 */
public final class Routes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.vehicle.grpc.Routes)
    RoutesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Routes.newBuilder() to construct.
  private Routes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Routes() {
    route_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Routes();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.vehicle.grpc.RouteManagerOuterClass.internal_static_com_vehicle_grpc_Routes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.vehicle.grpc.RouteManagerOuterClass.internal_static_com_vehicle_grpc_Routes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.vehicle.grpc.Routes.class, com.vehicle.grpc.Routes.Builder.class);
  }

  public static final int ROUTE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.vehicle.grpc.Route> route_;
  /**
   * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.vehicle.grpc.Route> getRouteList() {
    return route_;
  }
  /**
   * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.vehicle.grpc.RouteOrBuilder> 
      getRouteOrBuilderList() {
    return route_;
  }
  /**
   * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
   */
  @java.lang.Override
  public int getRouteCount() {
    return route_.size();
  }
  /**
   * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
   */
  @java.lang.Override
  public com.vehicle.grpc.Route getRoute(int index) {
    return route_.get(index);
  }
  /**
   * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
   */
  @java.lang.Override
  public com.vehicle.grpc.RouteOrBuilder getRouteOrBuilder(
      int index) {
    return route_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < route_.size(); i++) {
      output.writeMessage(1, route_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < route_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, route_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.vehicle.grpc.Routes)) {
      return super.equals(obj);
    }
    com.vehicle.grpc.Routes other = (com.vehicle.grpc.Routes) obj;

    if (!getRouteList()
        .equals(other.getRouteList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRouteCount() > 0) {
      hash = (37 * hash) + ROUTE_FIELD_NUMBER;
      hash = (53 * hash) + getRouteList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.vehicle.grpc.Routes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vehicle.grpc.Routes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vehicle.grpc.Routes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vehicle.grpc.Routes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vehicle.grpc.Routes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vehicle.grpc.Routes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vehicle.grpc.Routes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.vehicle.grpc.Routes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.vehicle.grpc.Routes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.vehicle.grpc.Routes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.vehicle.grpc.Routes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.vehicle.grpc.Routes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.vehicle.grpc.Routes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.vehicle.grpc.Routes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.vehicle.grpc.Routes)
      com.vehicle.grpc.RoutesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vehicle.grpc.RouteManagerOuterClass.internal_static_com_vehicle_grpc_Routes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vehicle.grpc.RouteManagerOuterClass.internal_static_com_vehicle_grpc_Routes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vehicle.grpc.Routes.class, com.vehicle.grpc.Routes.Builder.class);
    }

    // Construct using com.vehicle.grpc.Routes.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (routeBuilder_ == null) {
        route_ = java.util.Collections.emptyList();
      } else {
        route_ = null;
        routeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.vehicle.grpc.RouteManagerOuterClass.internal_static_com_vehicle_grpc_Routes_descriptor;
    }

    @java.lang.Override
    public com.vehicle.grpc.Routes getDefaultInstanceForType() {
      return com.vehicle.grpc.Routes.getDefaultInstance();
    }

    @java.lang.Override
    public com.vehicle.grpc.Routes build() {
      com.vehicle.grpc.Routes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.vehicle.grpc.Routes buildPartial() {
      com.vehicle.grpc.Routes result = new com.vehicle.grpc.Routes(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.vehicle.grpc.Routes result) {
      if (routeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          route_ = java.util.Collections.unmodifiableList(route_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.route_ = route_;
      } else {
        result.route_ = routeBuilder_.build();
      }
    }

    private void buildPartial0(com.vehicle.grpc.Routes result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.vehicle.grpc.Routes) {
        return mergeFrom((com.vehicle.grpc.Routes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.vehicle.grpc.Routes other) {
      if (other == com.vehicle.grpc.Routes.getDefaultInstance()) return this;
      if (routeBuilder_ == null) {
        if (!other.route_.isEmpty()) {
          if (route_.isEmpty()) {
            route_ = other.route_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRouteIsMutable();
            route_.addAll(other.route_);
          }
          onChanged();
        }
      } else {
        if (!other.route_.isEmpty()) {
          if (routeBuilder_.isEmpty()) {
            routeBuilder_.dispose();
            routeBuilder_ = null;
            route_ = other.route_;
            bitField0_ = (bitField0_ & ~0x00000001);
            routeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRouteFieldBuilder() : null;
          } else {
            routeBuilder_.addAllMessages(other.route_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.vehicle.grpc.Route m =
                  input.readMessage(
                      com.vehicle.grpc.Route.parser(),
                      extensionRegistry);
              if (routeBuilder_ == null) {
                ensureRouteIsMutable();
                route_.add(m);
              } else {
                routeBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.vehicle.grpc.Route> route_ =
      java.util.Collections.emptyList();
    private void ensureRouteIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        route_ = new java.util.ArrayList<com.vehicle.grpc.Route>(route_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.vehicle.grpc.Route, com.vehicle.grpc.Route.Builder, com.vehicle.grpc.RouteOrBuilder> routeBuilder_;

    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public java.util.List<com.vehicle.grpc.Route> getRouteList() {
      if (routeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(route_);
      } else {
        return routeBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public int getRouteCount() {
      if (routeBuilder_ == null) {
        return route_.size();
      } else {
        return routeBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public com.vehicle.grpc.Route getRoute(int index) {
      if (routeBuilder_ == null) {
        return route_.get(index);
      } else {
        return routeBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public Builder setRoute(
        int index, com.vehicle.grpc.Route value) {
      if (routeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRouteIsMutable();
        route_.set(index, value);
        onChanged();
      } else {
        routeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public Builder setRoute(
        int index, com.vehicle.grpc.Route.Builder builderForValue) {
      if (routeBuilder_ == null) {
        ensureRouteIsMutable();
        route_.set(index, builderForValue.build());
        onChanged();
      } else {
        routeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public Builder addRoute(com.vehicle.grpc.Route value) {
      if (routeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRouteIsMutable();
        route_.add(value);
        onChanged();
      } else {
        routeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public Builder addRoute(
        int index, com.vehicle.grpc.Route value) {
      if (routeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRouteIsMutable();
        route_.add(index, value);
        onChanged();
      } else {
        routeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public Builder addRoute(
        com.vehicle.grpc.Route.Builder builderForValue) {
      if (routeBuilder_ == null) {
        ensureRouteIsMutable();
        route_.add(builderForValue.build());
        onChanged();
      } else {
        routeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public Builder addRoute(
        int index, com.vehicle.grpc.Route.Builder builderForValue) {
      if (routeBuilder_ == null) {
        ensureRouteIsMutable();
        route_.add(index, builderForValue.build());
        onChanged();
      } else {
        routeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public Builder addAllRoute(
        java.lang.Iterable<? extends com.vehicle.grpc.Route> values) {
      if (routeBuilder_ == null) {
        ensureRouteIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, route_);
        onChanged();
      } else {
        routeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public Builder clearRoute() {
      if (routeBuilder_ == null) {
        route_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        routeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public Builder removeRoute(int index) {
      if (routeBuilder_ == null) {
        ensureRouteIsMutable();
        route_.remove(index);
        onChanged();
      } else {
        routeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public com.vehicle.grpc.Route.Builder getRouteBuilder(
        int index) {
      return getRouteFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public com.vehicle.grpc.RouteOrBuilder getRouteOrBuilder(
        int index) {
      if (routeBuilder_ == null) {
        return route_.get(index);  } else {
        return routeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public java.util.List<? extends com.vehicle.grpc.RouteOrBuilder> 
         getRouteOrBuilderList() {
      if (routeBuilder_ != null) {
        return routeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(route_);
      }
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public com.vehicle.grpc.Route.Builder addRouteBuilder() {
      return getRouteFieldBuilder().addBuilder(
          com.vehicle.grpc.Route.getDefaultInstance());
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public com.vehicle.grpc.Route.Builder addRouteBuilder(
        int index) {
      return getRouteFieldBuilder().addBuilder(
          index, com.vehicle.grpc.Route.getDefaultInstance());
    }
    /**
     * <code>repeated .com.vehicle.grpc.Route route = 1;</code>
     */
    public java.util.List<com.vehicle.grpc.Route.Builder> 
         getRouteBuilderList() {
      return getRouteFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.vehicle.grpc.Route, com.vehicle.grpc.Route.Builder, com.vehicle.grpc.RouteOrBuilder> 
        getRouteFieldBuilder() {
      if (routeBuilder_ == null) {
        routeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.vehicle.grpc.Route, com.vehicle.grpc.Route.Builder, com.vehicle.grpc.RouteOrBuilder>(
                route_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        route_ = null;
      }
      return routeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.vehicle.grpc.Routes)
  }

  // @@protoc_insertion_point(class_scope:com.vehicle.grpc.Routes)
  private static final com.vehicle.grpc.Routes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.vehicle.grpc.Routes();
  }

  public static com.vehicle.grpc.Routes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Routes>
      PARSER = new com.google.protobuf.AbstractParser<Routes>() {
    @java.lang.Override
    public Routes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Routes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Routes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.vehicle.grpc.Routes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

