// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_manager.proto

// Protobuf Java Version: 3.25.1
package com.vehicle.grpc;

public final class RouteManagerOuterClass {
  private RouteManagerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vehicle_grpc_Route_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vehicle_grpc_Route_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vehicle_grpc_Routes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vehicle_grpc_Routes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vehicle_grpc_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vehicle_grpc_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vehicle_grpc_RouteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vehicle_grpc_RouteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vehicle_grpc_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vehicle_grpc_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023route_manager.proto\022\020com.vehicle.grpc\"" +
      "A\n\005Route\022\'\n\006events\030\001 \003(\0132\027.com.vehicle.g" +
      "rpc.Event\022\017\n\007vehicle\030\002 \001(\t\"0\n\006Routes\022&\n\005" +
      "route\030\001 \003(\0132\027.com.vehicle.grpc.Route\"\031\n\005" +
      "Event\022\020\n\010location\030\001 \001(\t\">\n\rRouteResponse" +
      "\022-\n\006result\030\001 \001(\0162\035.com.vehicle.grpc.Rout" +
      "eResult\"\007\n\005Empty*I\n\013RouteResult\022\013\n\007Succe" +
      "ss\020\000\022\022\n\016UnknownVehicle\020\001\022\031\n\014UnknownError" +
      "\020\377\377\377\377\377\377\377\377\377\0012W\n\016VehicleService\022E\n\007vehicle" +
      "\022\027.com.vehicle.grpc.Route\032\037.com.vehicle." +
      "grpc.RouteResponse\"\0002\223\001\n\014RouteManager\022D\n" +
      "\010AddRoute\022\027.com.vehicle.grpc.Route\032\037.com" +
      ".vehicle.grpc.RouteResponse\022=\n\tGetRoutes" +
      "\022\027.com.vehicle.grpc.Empty\032\027.com.vehicle." +
      "grpc.RouteB\024\n\020com.vehicle.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_vehicle_grpc_Route_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_vehicle_grpc_Route_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vehicle_grpc_Route_descriptor,
        new java.lang.String[] { "Events", "Vehicle", });
    internal_static_com_vehicle_grpc_Routes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_vehicle_grpc_Routes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vehicle_grpc_Routes_descriptor,
        new java.lang.String[] { "Route", });
    internal_static_com_vehicle_grpc_Event_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_vehicle_grpc_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vehicle_grpc_Event_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_com_vehicle_grpc_RouteResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_vehicle_grpc_RouteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vehicle_grpc_RouteResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_vehicle_grpc_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_vehicle_grpc_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vehicle_grpc_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
